#!/usr/bin/env bash

if [[ -z "${SAFE_BATTERY_LEVEL}" ]]; then
	SAFE_BATTERY_LEVEL=15
fi

if [[ -n "${NOTIF_TIMEOUT_MILLIS}" ]]; then
	OPT_NOTIF_TIMEOUT_MILLIS="-t ${NOTIF_TIMEOUT_MILLIS}"
fi

status=$(</sys/class/power_supply/BAT0/status)
capacity=$(</sys/class/power_supply/BAT0/capacity)

if [[ $capacity -lt $SAFE_BATTERY_LEVEL && $status == "Discharging" ]]; then
  notify-send $OPT_NOTIF_TIMEOUT -u critical "Battery level critical!" \
	  "Connect Charger  <br />Battery level is at ${capacity}%"
fi
